-- AI weekly insight reports — generated by the insights bot (lib/ai/bots/
-- insights-bot.ts) from the deterministic metrics in lib/insights/metrics.ts.
-- One row per (property, week, audience); the unique index makes generation
-- idempotent and the metrics/anomalies jsonb columns preserve exactly what
-- the model was shown, so a report is auditable against its inputs.

create table public.insight_reports (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  audience text not null check (audience in ('management','staff')),
  summary_md text not null,
  metrics jsonb not null,
  anomalies jsonb not null default '[]'::jsonb,
  model text not null,
  trace jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index insight_reports_period_key
  on public.insight_reports (property_id, period_start, audience);

create index insight_reports_property_idx
  on public.insight_reports (property_id, period_start desc);

alter table public.insight_reports enable row level security;

-- Staff-audience reports are readable by any member; management reports
-- require owner/manager. Writes happen only via the service-role client in
-- the report API route, so no insert/update/delete policies.
create policy insight_reports_select on public.insight_reports
  for select using (
    public.is_member(property_id)
    and (
      audience = 'staff'
      or exists (
        select 1 from public.memberships m
        where m.property_id = insight_reports.property_id
          and m.user_id = auth.uid()
          and m.role in ('owner','manager')
      )
    )
  );

-- Publish so a freshly generated report pushes to open Reports views.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'insight_reports'
  ) then
    alter publication supabase_realtime add table public.insight_reports;
  end if;
end $$;
