-- Forms & feedback — property-scoped forms built in the form builder (or
-- generated by AI), filled from the Forms section, a chat embed, a workflow
-- step, or onboarding. The field list lives in `schema` as versioned JSON
-- (see lib/forms/schema.ts) so the builder, renderer, and AI generator all
-- share one shape; answers are stored as {fieldId: value} JSON keyed by the
-- schema's field ids.

create table public.forms (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  title text not null,
  description text,
  icon text,
  schema jsonb not null default '{"version":1,"fields":[]}'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published', 'closed')),
  -- Multiple responses per person (e.g. maintenance request) vs one (e.g. survey).
  allow_multiple boolean not null default true,
  -- Anonymous forms never store respondent_id, so staff feedback can be honest.
  anonymous boolean not null default false,
  space_id uuid references public.spaces(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index forms_property_idx on public.forms (property_id, created_at desc);
create index forms_space_idx on public.forms (space_id) where space_id is not null;

create trigger forms_touch_updated_at
  before update on public.forms
  for each row execute function public.touch_updated_at();

create table public.form_responses (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.forms(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,
  -- Null when the form is anonymous (or a future external respondent).
  respondent_id uuid references auth.users(id) on delete set null,
  answers jsonb not null default '{}'::jsonb,
  source text not null default 'direct' check (source in ('direct', 'chat', 'workflow', 'onboarding')),
  created_at timestamptz not null default now()
);

create index form_responses_form_idx on public.form_responses (form_id, created_at desc);
create index form_responses_property_idx on public.form_responses (property_id, created_at desc);

alter table public.forms enable row level security;
alter table public.form_responses enable row level security;

-- Any property member can see and create forms; edits/deletes are by the
-- creator, with owners/managers able to manage any form (same trust model
-- the rest of the app uses — RLS scopes the tenant, the app scopes intent).
create policy forms_select on public.forms
  for select using (public.is_member(property_id));

create policy forms_insert on public.forms
  for insert with check (public.is_member(property_id) and created_by = auth.uid());

create policy forms_update on public.forms
  for update using (
    public.is_member(property_id)
    and (
      created_by = auth.uid()
      or exists (
        select 1 from public.memberships m
        where m.property_id = forms.property_id
          and m.user_id = auth.uid()
          and m.role in ('owner', 'manager')
      )
    )
  )
  with check (public.is_member(property_id));

create policy forms_delete on public.forms
  for delete using (
    public.is_member(property_id)
    and (
      created_by = auth.uid()
      or exists (
        select 1 from public.memberships m
        where m.property_id = forms.property_id
          and m.user_id = auth.uid()
          and m.role in ('owner', 'manager')
      )
    )
  );

-- Members submit responses to published forms in their property. Reading
-- responses is limited to the form's creator and owners/managers — feedback
-- forms shouldn't be browsable by every respondent.
create policy form_responses_insert on public.form_responses
  for insert with check (
    public.is_member(property_id)
    and exists (
      select 1 from public.forms f
      where f.id = form_responses.form_id
        and f.property_id = form_responses.property_id
        and f.status = 'published'
    )
  );

create policy form_responses_select on public.form_responses
  for select using (
    public.is_member(property_id)
    and (
      respondent_id = auth.uid()
      or exists (
        select 1 from public.forms f
        where f.id = form_responses.form_id and f.created_by = auth.uid()
      )
      or exists (
        select 1 from public.memberships m
        where m.property_id = form_responses.property_id
          and m.user_id = auth.uid()
          and m.role in ('owner', 'manager')
      )
    )
  );

-- Live response counts in the builder + forms list.
alter publication supabase_realtime add table public.forms;
alter publication supabase_realtime add table public.form_responses;

-- Onboarding profile — the answers the setup wizard captures about the
-- property (type, size, departments, priorities). Not derivable from any
-- other table; read by AI bots so their context is property-aware from the
-- first message.
create table public.property_profiles (
  property_id uuid primary key references public.properties(id) on delete cascade,
  property_type text,
  team_size text,
  departments jsonb not null default '[]'::jsonb,
  priorities jsonb not null default '[]'::jsonb,
  role_title text,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger property_profiles_touch_updated_at
  before update on public.property_profiles
  for each row execute function public.touch_updated_at();

alter table public.property_profiles enable row level security;

create policy property_profiles_select on public.property_profiles
  for select using (public.is_member(property_id));

create policy property_profiles_write on public.property_profiles
  for all using (
    exists (
      select 1 from public.memberships m
      where m.property_id = property_profiles.property_id
        and m.user_id = auth.uid()
        and m.role in ('owner', 'manager')
    )
  )
  with check (public.is_member(property_id));
